{% set name = "fast-depends" %}
{% set version = "3.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_depends-{{ version }}.tar.gz
  sha256: 896b16f79a512b6ea1df721b0aa1708a192a06f964be6597e01fcf5412559101

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - uv-build >=0.9.2
    - pip
  run:
    - python
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - anyio >=4.0.0,<5.0.0
    - msgspec

test:
  imports:
    - fast_depends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Lancetnik/FastDepends
  summary: FastDepends - extracted and cleared from HTTP domain logic FastAPI Dependency Injection System. Async and sync are both supported.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/Lancetnik/FastDepends
  doc_url: https://lancetnik.github.io/FastDepends/

extra:
  recipe-maintainers:
    - carlodri
